// common
export const COMMON_LOGIN_STORAGE = 'COMMON_LOGIN_STORAGE'
export const COMMON_LOGOUT = 'COMMON_LOGOUT'
export const COMMON_RESET = 'COMMON_RESET'
export const COMMON_FORGOT = 'COMMON_FORGOT'
export const COMMON_GET_TOKEN = 'COMMON_GET_TOKEN'
export const COMMON_SET_TOKEN = 'COMMON_SET_TOKEN'
export const COMMON_GET_USER = 'COMMON_GET_USER'
export const COMMON_SET_USER = 'COMMON_SET_USER'

// sms
export const SMS_SEND_LOGS = 'SMS_SEND_LOGS'
export const SMS_TPL_ADD = 'SMS_TPL_ADD'
export const SMS_TPL_LIST = 'SMS_TPL_LIST'

// user
export const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD'
